//*********************************************************
//
// Copyright (c) Microsoft. All rights reserved.
// THIS CODE IS PROVIDED *AS IS* WITHOUT WARRANTY OF
// ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING ANY
// IMPLIED WARRANTIES OF FITNESS FOR A PARTICULAR
// PURPOSE, MERCHANTABILITY, OR NON-INFRINGEMENT.
//
//*********************************************************
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace OktofsRateControllerNamespace
{
    /// <summary>
    /// Policy Modules provide entry points for upcalls from the controller.
    /// The callbacks happen on a single thread so they are guaranteed 
    /// threadsafe with respect to each other. 
    /// </summary>
    public interface IPolicyModule : IDisposable
    {
        /// <summary>
        /// Function called when settle interval has expired.
        /// </summary>
        void CallbackSettleTimeout();

        /// <summary>
        /// Function called when stats sampling interval has expited.
        /// </summary>
        void CallbackControlInterval();

        /// <summary>
        /// Function called when an unsolicited alert is received.
        /// An alerts may be generated by e.g. a local process or a remote agent.
        /// </summary>
        void CallbackAlert(MessageAlert messageAlert, RateControllerState state);
    }
}
